#include "insights/redaction.hpp"

namespace lubancode::insights {
namespace {

// allowlist 路径树:叶子=true 即许可。数组元素不进 path,同名键同裁。
// 与 report_model/session_summary/finding 的 ToJson 一一对应;schema 之外
// 的字段不许出现。
bool WalkAllowlist(const std::vector<std::string>& path) {
    static const std::vector<std::vector<std::string>> kAllowed = {
        {"schema"},
        {"schema_version"},
        {"analyzer_version"},
        {"generated_at"},
        {"analysis_mode"},
        {"scope", "workspace_key"},
        {"scope", "since"},
        {"scope", "until"},
        {"scope", "all_workspaces"},
        {"coverage", "sessions_found"},
        {"coverage", "sessions_verified"},
        {"coverage", "sessions_analyzed"},
        {"coverage", "sessions_pending"},
        {"coverage", "sessions_excluded"},
        {"coverage", "runs_total"},
        {"coverage", "runs_analyzed"},
        {"coverage", "requests_total"},
        {"coverage", "requests_with_usage"},
        {"coverage", "outcomes_assessed"},
        {"usage", "requests_total"},
        {"usage", "requests_with_usage"},
        {"usage", "requests_unknown"},
        {"usage", "input_tokens"},
        {"usage", "cache_read_tokens"},
        {"usage", "cache_creation_tokens"},
        {"usage", "output_tokens"},
        {"usage", "reasoning_tokens"},
        {"usage", "cost"},
        {"usage", "cost", "status"},
        {"usage", "cost", "currency"},
        {"usage", "cost", "micros"},
        {"usage", "cost", "price_table_id"},
        {"source", "session_id"},
        {"source", "stream_terminal_hashes"},
        {"source", "integrity"},
        {"source", "format"},
        {"coverage", "limitations"},
        {"work", "turns"},
        {"work", "tool_calls"},
        {"work", "files_touched"},
        {"work", "verifications"},
        {"work", "outcome"},
        {"prompt_findings"},
        {"prompt_findings", "finding_id"},
        {"prompt_findings", "category"},
        {"prompt_findings", "severity"},
        {"prompt_findings", "confidence"},
        {"prompt_findings", "scope"},
        {"prompt_findings", "evidence"},
        {"prompt_findings", "evidence", "session_id"},
        {"prompt_findings", "evidence", "event_id"},
        {"prompt_findings", "evidence", "seq"},
        {"prompt_findings", "evidence", "metric"},
        {"prompt_findings", "evidence", "value"},
        {"prompt_findings", "counter_evidence"},
        {"prompt_findings", "counter_evidence", "session_id"},
        {"prompt_findings", "counter_evidence", "event_id"},
        {"prompt_findings", "counter_evidence", "seq"},
        {"prompt_findings", "counter_evidence", "metric"},
        {"prompt_findings", "counter_evidence", "value"},
        {"prompt_findings", "summary"},
        {"prompt_findings", "recommendation"},
        {"prompt_findings", "origin"},
        {"prompt_findings", "rule_version"},
        {"friction_events"},
        {"feature_signals"},
        {"sessions"},
        {"sessions", "schema"},
        {"sessions", "schema_version"},
        {"sessions", "analyzer_version"},
        {"sessions", "source", "session_id"},
        {"sessions", "source", "stream_terminal_hashes"},
        {"sessions", "source", "integrity"},
        {"sessions", "source", "format"},
        {"sessions", "coverage", "runs_total"},
        {"sessions", "coverage", "runs_analyzed"},
        {"sessions", "coverage", "requests_total"},
        {"sessions", "coverage", "requests_with_usage"},
        {"sessions", "coverage", "outcomes_assessed"},
        {"sessions", "coverage", "limitations"},
        {"sessions", "work", "turns"},
        {"sessions", "work", "tool_calls"},
        {"sessions", "work", "files_touched"},
        {"sessions", "work", "verifications"},
        {"sessions", "work", "outcome"},
        {"sessions", "usage", "requests_total"},
        {"sessions", "usage", "requests_with_usage"},
        {"sessions", "usage", "input_tokens"},
        {"sessions", "usage", "cache_read_tokens"},
        {"sessions", "usage", "cache_creation_tokens"},
        {"sessions", "usage", "output_tokens"},
        {"sessions", "usage", "reasoning_tokens"},
        {"sessions", "usage", "cost", "status"},
        {"sessions", "usage", "cost", "currency"},
        {"sessions", "usage", "cost", "micros"},
        {"sessions", "usage", "cost", "price_table_id"},
        {"sessions", "prompt_findings", "finding_id"},
        {"sessions", "prompt_findings", "category"},
        {"sessions", "prompt_findings", "severity"},
        {"sessions", "prompt_findings", "confidence"},
        {"sessions", "prompt_findings", "scope"},
        {"sessions", "prompt_findings", "evidence", "session_id"},
        {"sessions", "prompt_findings", "evidence", "event_id"},
        {"sessions", "prompt_findings", "evidence", "seq"},
        {"sessions", "prompt_findings", "evidence", "metric"},
        {"sessions", "prompt_findings", "evidence", "value"},
        {"sessions", "prompt_findings", "counter_evidence", "session_id"},
        {"sessions", "prompt_findings", "counter_evidence", "event_id"},
        {"sessions", "prompt_findings", "counter_evidence", "seq"},
        {"sessions", "prompt_findings", "counter_evidence", "metric"},
        {"sessions", "prompt_findings", "counter_evidence", "value"},
        {"sessions", "prompt_findings", "summary"},
        {"sessions", "prompt_findings", "recommendation"},
        {"sessions", "prompt_findings", "origin"},
        {"sessions", "prompt_findings", "rule_version"},
        {"sessions", "friction_events"},
        {"sessions", "feature_signals"},
        {"findings"},
        {"findings", "finding_id"},
        {"findings", "category"},
        {"findings", "severity"},
        {"findings", "confidence"},
        {"findings", "scope"},
        {"findings", "evidence"},
        {"findings", "evidence", "session_id"},
        {"findings", "evidence", "event_id"},
        {"findings", "evidence", "seq"},
        {"findings", "evidence", "metric"},
        {"findings", "evidence", "value"},
        {"findings", "counter_evidence"},
        {"findings", "counter_evidence", "session_id"},
        {"findings", "counter_evidence", "event_id"},
        {"findings", "counter_evidence", "seq"},
        {"findings", "counter_evidence", "metric"},
        {"findings", "counter_evidence", "value"},
        {"findings", "summary"},
        {"findings", "recommendation"},
        {"findings", "origin"},
        {"findings", "rule_version"},
    };
    for (const auto& allowed : kAllowed) {
        if (allowed == path) {
            return true;
        }
    }
    return false;
}

}  // namespace

bool IsAllowedReportFieldPath(const std::vector<std::string>& path) {
    return WalkAllowlist(path);
}

}  // namespace lubancode::insights
